runtime: python39

env_variables:
  OPENAI_API_KEY: "your_openai_api_key_here"

automatic_scaling:
  min_instances: 1
  max_instances: 10
  target_cpu_utilization: 0.6

resources:
  cpu: 1
  memory_gb: 2
